###
# Compose file to launch  build and test slave.  Build will be performed build salve, output folder is
# shared between two build and test salve.
####
version: '3.7'
services:
  build-slave:
    image: dipinthomas2003/android_build_slave:23.0.2
    volumes:
      - /root/docker/apk_share:/root/workspace/

  test-slave:
    image: dipinthomas2003/appium_slave:1.10.1
    ports:
     - 4723:4723
    volumes:
      - /root/docker/apk_share/mobile-ci-build:/root/workspace/mobile-ci-test/
      - /dev/bus/usb:/dev/bus/usb
    privileged: true