FROM dipinthomas2003/android_base:23.0.2


# Copy Agent
COPY agent.jar . 

#make agent
CMD adb devices &&  java -jar agent.jar -jnlpUrl http://<REPLACE_ME_CI_SYSTEM>/computer/Appium-Container/slave-agent.jnlp -secret <SECRET_CHANGE_ME> -workDir "<CHANGE_ME_WORKSPACE>"
