FROM dipinthomas2003/android_base:23.0.2

ENV DEBIAN_FRONTEND=noninteractive

ARG APPIUM_VERSION=1.10.1
ENV APPIUM_VERSION=$APPIUM_VERSION

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get -qqy install nodejs && \
    npm install -g appium@${APPIUM_VERSION} --unsafe-perm=true --allow-root 


# Copy Agent
COPY agent.jar . 

#make agent
CMD java -jar agent.jar -jnlpUrl http://139.59.74.73:8080/computer/Appium-Container/slave-agent.jnlp -secret aed5f582d474e4525893c372859398f2314c0311f08211e482109cb4a993815b -workDir "/User/Admin/jenkins-local"
